# Generated by Django 5.1.4 on 2025-02-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
